apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crd
  namespace: argocd
  labels:
    name: kube-prometheus-stack-crd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: "https://github.com/prometheus-community/helm-charts.git"
    targetRevision: "kube-prometheus-stack-55.5.0"
    path: "charts/kube-prometheus-stack/charts/crds/crds"
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack-crd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=ture
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - Replace=true
    retry:
      limit:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 4m
  revisionHistoryLimit: 10